///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 13.0.3
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#endif



using namespace HalconCpp;

// Procedure declarations 
void CircularSector (HTuple hv_isz, HTuple hv_n, HTuple hv_ki, HTuple *hv_K);
// Procedures 
void CircularSector (HTuple hv_isz, HTuple hv_n, HTuple hv_ki, HTuple *hv_K)
{

  // Local iconic variables

  // Local control variables
  HTuple  hv_kb, hv_ke;

  //***CircularSector 03.09.2025
  hv_kb = hv_ki-hv_isz;
  if (0 != (hv_kb<0))
  {
    hv_kb = hv_n+hv_kb;
  }
  hv_ke = (hv_ki+hv_isz)-1;
  if (0 != (hv_ke>=hv_n))
  {
    hv_ke = hv_ke-hv_n;
  }

  if (0 != (hv_kb<=hv_ke))
  {
    (*hv_K) = HTuple::TupleGenSequence(hv_kb,hv_ke,1);
  }
  else
  {

    (*hv_K).Clear();
    (*hv_K).Append(HTuple::TupleGenSequence(0,hv_ke,1));
    (*hv_K).Append(HTuple::TupleGenSequence(hv_kb,hv_n-1,1));
  }

  return;
}


