///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 13.0.3
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#endif



using namespace HalconCpp;

// Procedure declarations 
void BuildBorderContour (HObject ho_Bordersi, HObject *ho_Bordercl);
void BuildRealContour (HObject ho_Im, HObject ho_Rectangle5, HObject *ho_ContourOut, 
    HObject *ho_RegionIR, HTuple hv_ctype, HTuple hv_thr);
void Region_Threshold_SubPix (HObject ho_RegSel, HObject ho_Im, HTuple hv_Thr, HTuple *hv_RowsSub, 
    HTuple *hv_ColsSub);
// Procedures 
void BuildBorderContour (HObject ho_Bordersi, HObject *ho_Bordercl)
{

  // Local iconic variables
  HObject  ho_Borders, ho_Border;

  // Local control variables
  HTuple  hv_nB, hv_LengthBI, hv_Indices, hv_Inverted;
  HTuple  hv_imax1, hv_imax2;

  CountObj(ho_Bordersi, &hv_nB);
  LengthXld(ho_Bordersi, &hv_LengthBI);
  TupleSortIndex(hv_LengthBI, &hv_Indices);
  TupleInverse(hv_Indices, &hv_Inverted);
  hv_imax1 = HTuple(hv_Inverted[0])+1;
  if (0 != (hv_nB>1))
  {
    hv_imax2 = HTuple(hv_Inverted[1])+1;
    //* check if there's only one boundary contour
    if (0 != (HTuple(hv_LengthBI[hv_imax2-1])<(HTuple(hv_LengthBI[hv_imax1-1])/2)))
    {
      hv_imax2 = HTuple();
    }
    SelectObj(ho_Bordersi, &ho_Borders, hv_imax1.TupleConcat(hv_imax2));
  }
  else
  {
    ho_Borders = ho_Bordersi;
  }
  UnionAdjacentContoursXld(ho_Borders, &ho_Border, 25, 25, "attr_forget");
  //test_closed_xld (Border, IsClosed)
  CloseContoursXld(ho_Border, &(*ho_Bordercl));
  return;
}

void Region_Threshold_SubPix (HObject ho_RegSel, HObject ho_Im, HTuple hv_Thr, HTuple *hv_RowsSub, 
    HTuple *hv_ColsSub)
{

  // Local iconic variables
  HObject  ho_Cross;

  // Local control variables
  HTuple  hv_Pos_Sub, hv_Im_W, hv_Im_H, hv_Rows;
  HTuple  hv_Cols, hv_Cont_Len, hv_Pos, hv_Gray0, hv_Hole;
  HTuple  hv_Pos_Next, hv_Pos_Prev, hv_Row_Prev, hv_Col_Prev;
  HTuple  hv_Row_Next, hv_Col_Next, hv_Row_Curr, hv_Col_Curr;
  HTuple  hv_Down, hv_Left, hv_Gray1, hv_Gray2, hv_X0, hv_X1;
  HTuple  hv_X2, hv_Xr1, hv_Y1, hv_Y2, hv_Yr1, hv_Yr2, hv_Xr2;

  (*hv_RowsSub) = HTuple();
  (*hv_ColsSub) = HTuple();
  hv_Pos_Sub = 0;

  GetImageSize(ho_Im, &hv_Im_W, &hv_Im_H);
  GetRegionContour(ho_RegSel, &hv_Rows, &hv_Cols);
  TupleLength(hv_Rows, &hv_Cont_Len);

  //???? ?? ?????
  {
  HTuple end_val9 = hv_Cont_Len-1;
  HTuple step_val9 = 1;
  for (hv_Pos=0; hv_Pos.Continue(end_val9, step_val9); hv_Pos += step_val9)
  {
    GetGrayval(ho_Im, HTuple(hv_Rows[hv_Pos]), HTuple(hv_Cols[hv_Pos]), &hv_Gray0);

    if (0 != (hv_Gray0<hv_Thr))
    {
      hv_Hole = 1;
      break;
    }
    else if (0 != (hv_Gray0>hv_Thr))
    {
      hv_Hole = 0;
      break;
    }

  }
  }


  {
  HTuple end_val23 = hv_Cont_Len-1;
  HTuple step_val23 = 1;
  for (hv_Pos=0; hv_Pos.Continue(end_val23, step_val23); hv_Pos += step_val23)
  {
    GetGrayval(ho_Im, HTuple(hv_Rows[hv_Pos]), HTuple(hv_Cols[hv_Pos]), &hv_Gray0);

    hv_Pos_Next = hv_Pos+1;
    if (0 != (hv_Pos_Next>(hv_Cont_Len-1)))
    {
      hv_Pos_Next = 0;
    }
    hv_Pos_Prev = hv_Pos-1;
    if (0 != (hv_Pos_Prev<0))
    {
      hv_Pos_Prev = hv_Cont_Len-1;
    }
    hv_Row_Prev = HTuple(hv_Rows[hv_Pos_Prev]);
    hv_Col_Prev = HTuple(hv_Cols[hv_Pos_Prev]);
    hv_Row_Next = HTuple(hv_Rows[hv_Pos_Next]);
    hv_Col_Next = HTuple(hv_Cols[hv_Pos_Next]);
    hv_Row_Curr = HTuple(hv_Rows[hv_Pos]);
    hv_Col_Curr = HTuple(hv_Cols[hv_Pos]);

    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"red");
    GenCrossContourXld(&ho_Cross, hv_Row_Curr, hv_Col_Curr, 1, 0);


    if (0 != (HTuple(HTuple(HTuple(hv_Row_Curr>=(hv_Im_H-1)).TupleOr(hv_Col_Curr>=(hv_Im_W-1))).TupleOr(hv_Row_Curr==0)).TupleOr(hv_Col_Curr==0)))
    {
      continue;
    }

    //???????????
    if (0 != (HTuple(hv_Row_Curr>hv_Row_Prev).TupleOr(hv_Row_Curr<hv_Row_Next)))
    {
      hv_Down = 1;
    }
    else
    {
      hv_Down = 0;
    }

    if (0 != (HTuple(hv_Col_Curr<hv_Col_Prev).TupleOr(hv_Col_Curr>hv_Col_Next)))
    {
      hv_Left = 1;
    }
    else
    {
      hv_Left = 0;
    }

    //-- Cols -------------------------------------------
    GetGrayval(ho_Im, hv_Row_Curr, hv_Col_Curr+1, &hv_Gray1);
    GetGrayval(ho_Im, hv_Row_Curr, hv_Col_Curr-1, &hv_Gray2);
    hv_X0 = -1;
    hv_X1 = 0;
    hv_X2 = 0;
    hv_Xr1 = -1;

    //???? ????. ?????????? ? ????? ??????
    if (0 != (hv_Down.TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray1>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray1<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray0;
      hv_X2 = hv_Gray1;
      hv_Y1 = HTuple(hv_Cols[hv_Pos]);
      hv_Y2 = HTuple(hv_Cols[hv_Pos])+1;
      //???? ?????. ?????????? ? ????? ?????
    }
    else if (0 != (HTuple(hv_Down.TupleNot()).TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray2>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray2<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray2;
      hv_X2 = hv_Gray0;
      hv_Y1 = HTuple(hv_Cols[hv_Pos])-1;
      hv_Y2 = HTuple(hv_Cols[hv_Pos]);
    }

    if (0 != (HTuple(hv_X0>=0).TupleAnd(hv_X2!=hv_X1)))
    {
      hv_Xr1 = (hv_Y1.TupleReal())+((((hv_X0-hv_X1).TupleReal())*((hv_Y2-hv_Y1).TupleReal()))/((hv_X2-hv_X1).TupleReal()));
      hv_Yr1 = HTuple(hv_Rows[hv_Pos]);

      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),"green");
      GenCrossContourXld(&ho_Cross, hv_Yr1, hv_Xr1, 0.5, 0);
    }

    //--- Rows -------------------------------------------
    GetGrayval(ho_Im, hv_Row_Curr+1, hv_Col_Curr, &hv_Gray1);
    GetGrayval(ho_Im, hv_Row_Curr-1, hv_Col_Curr, &hv_Gray2);
    hv_X0 = -1;
    hv_Yr2 = -1;

    //???? ?????. ?????????? ? ????? ?????
    if (0 != (hv_Left.TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray1>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray1<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray0;
      hv_X2 = hv_Gray1;
      hv_Y1 = HTuple(hv_Rows[hv_Pos]);
      hv_Y2 = HTuple(hv_Rows[hv_Pos])+1;
      //???? ??????. ?????????? ? ????? ??????
    }
    else if (0 != (HTuple(hv_Left.TupleNot()).TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray2>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray2<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray2;
      hv_X2 = hv_Gray0;
      hv_Y1 = HTuple(hv_Rows[hv_Pos])-1;
      hv_Y2 = HTuple(hv_Rows[hv_Pos]);
    }

    if (0 != (HTuple(hv_X0>=0).TupleAnd(hv_X2!=hv_X1)))
    {
      hv_Yr2 = (hv_Y1.TupleReal())+((((hv_X0-hv_X1).TupleReal())*((hv_Y2-hv_Y1).TupleReal()))/((hv_X2-hv_X1).TupleReal()));
      hv_Xr2 = HTuple(hv_Cols[hv_Pos]);

      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),"red");
      GenCrossContourXld(&ho_Cross, hv_Yr2, hv_Xr2, 0.5, 0);
    }



    if (0 != (HTuple(hv_Xr1>=0).TupleAnd(hv_Yr2>=0)))
    {
      if (0 != (hv_Xr1>hv_Xr2))
      {
        if (0 != (hv_Yr1>hv_Yr2))
        {
          //Yr_Avg := (Yr2 + Yr1) / 2
          //Xr_Avg := (Xr2 + Xr1) / 2

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;
        }
        else
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;
        }
      }
      else
      {
        if (0 != (hv_Yr1<hv_Yr2))
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;
        }
        else
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;
        }
      }
    }
    else if (0 != (hv_Xr1>=0))
    {
      (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
      (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
      hv_Pos_Sub += 1;
    }
    else if (0 != (hv_Yr2>=0))
    {
      (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
      (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
      hv_Pos_Sub += 1;
    }

  }
  }
  return;
}

void BuildRealContour (HObject ho_Im, HObject ho_Rectangle5, HObject *ho_ContourOut, 
    HObject *ho_RegionIR, HTuple hv_ctype, HTuple hv_thr)
{

  // Local iconic variables
  HObject  ho_Bordersi, ho_ContourH, ho_RegionIr;
  HObject  ho_RegionsIR, ho_ContourIK;

  // Local control variables
  HTuple  hv_RowsSubI, hv_ColsSubI, hv_AreaI, hv_RowIK;
  HTuple  hv_ColIK, hv_PointOrderG, hv_AreaIR, hv_Row, hv_Column;
  HTuple  hv_Indices, hv_Inverted;

  //** BuildRealContour 11.09.2025
  if (0 != (hv_ctype==1))
  {
    //* H
    //reduce_domain (Im, Rectangle5, ImageReduced)
    ThresholdSubPix(ho_Im, &ho_Bordersi, hv_thr);
    BuildBorderContour(ho_Bordersi, &ho_ContourH);
    GetContourXld(ho_ContourH, &hv_RowsSubI, &hv_ColsSubI);
    AreaCenterXld(ho_ContourH, &hv_AreaI, &hv_RowIK, &hv_ColIK, &hv_PointOrderG);
    GenRegionContourXld(ho_ContourH, &(*ho_RegionIR), "filled");
    (*ho_ContourOut) = ho_ContourH;
    //H end
  }
  else
  {
    //* IK
    Threshold(ho_Im, &ho_RegionIr, hv_thr, 255);
    Intersection(ho_RegionIr, ho_Rectangle5, &(*ho_RegionIR));
    Connection((*ho_RegionIR), &ho_RegionsIR);
    AreaCenter(ho_RegionsIR, &hv_AreaIR, &hv_Row, &hv_Column);
    TupleSortIndex(hv_AreaIR, &hv_Indices);
    TupleInverse(hv_Indices, &hv_Inverted);
    SelectObj(ho_RegionsIR, &(*ho_RegionIR), HTuple(hv_Inverted[0])+1);
    Region_Threshold_SubPix((*ho_RegionIR), ho_Im, hv_thr, &hv_RowsSubI, &hv_ColsSubI);
    GenContourPolygonXld(&ho_ContourIK, hv_RowsSubI, hv_ColsSubI);
    (*ho_ContourOut) = ho_ContourIK;
    //* IK end
  }
  return;
}


