///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 13.0.3
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#endif



using namespace HalconCpp;

// Procedure declarations 
void DistanceContours2H (HTuple hv_RowI, HTuple hv_ColI, HTuple hv_RowG, HTuple hv_ColG, 
    HTuple hv_isz, HTuple *hv_D);
void DistPointToLineSegmH (HTuple hv_y, HTuple hv_x, HTuple hv_y1, HTuple hv_x1, HTuple hv_y2, 
    HTuple hv_x2, HTuple *hv_distance, HTuple *hv_ym, HTuple *hv_xm, HTuple *hv_t);


void MeasureDisplacementH (HObject ho_Im, HObject ho_RegionInoD, HObject ho_MeanderRects, 
    HObject ho_RegionsGrMe, HObject ho_ContourGrsm, HTuple hv_meander, HTuple hv_thr, 
    HTuple hv_RowGsm, HTuple hv_ColGsm, HTuple *hv_Displacement);
void MoveContourH (HObject ho_Contour, HObject *ho_ContourOut, HTuple hv_mr, HTuple hv_mc);
void Region_Threshold_SubPixH (HObject ho_RegSel, HObject ho_Im, HTuple hv_Thr, HTuple *hv_RowsSub, 
    HTuple *hv_ColsSub);
void ReverseContourH (HObject ho_ContourIn, HObject *ho_ContourOut);
// Procedures 



void DistanceContours2H (HTuple hv_RowI, HTuple hv_ColI, HTuple hv_RowG, HTuple hv_ColG, 
    HTuple hv_isz, HTuple *hv_D)
{

  // Local iconic variables
  HObject  ho_CI, ho_CG, ho_CG1, ho_CG2;

  // Local control variables
  HTuple  hv_nI, hv_nG, hv_ki, hv_iz, hv_i, hv_colI;
  HTuple  hv_rowI, hv_kb, hv_ke, hv_ColGs, hv_RowGs, hv_K;
  HTuple  hv_num, hv_DIGcOut, hv_DIGr, hv_DIGs, hv_IndicesD;
  HTuple  hv_minD, hv_k, hv_rowG, hv_colG, hv_ki1, hv_colG1;
  HTuple  hv_rowG1, hv_ki2, hv_colG2, hv_rowG2, hv_d1, hv_rowm1;
  HTuple  hv_colGm1, hv_t1, hv_d2, hv_rowm2, hv_colGm2, hv_t2;
  HTuple  hv_d, hv_dd, hv_kim2, hv_rowGm1, hv_dm1, hv_tm1;
  HTuple  hv_kip2, hv_colGp2, hv_rowGp2, hv_dp2, hv_tp2;

  //***** DistanceContours2 (RowI, ColI, RowG, ColG, isz, DistIG)
  //*** finding distance betweel contours given as points
  //*** 02.09.2025

  hv_nI = hv_RowI.TupleLength();
  hv_nG = hv_RowG.TupleLength();
  hv_ki = 0;
  hv_iz = hv_isz;
  {
  HTuple end_val8 = hv_nI-1;
  HTuple step_val8 = 1;
  for (hv_i=0; hv_i.Continue(end_val8, step_val8); hv_i += step_val8)
  {

    if (0 != (hv_i==0))
    {
      hv_isz = hv_nI/2;
    }
    else
    {
      hv_isz = hv_iz;
    }

    //if (i==876)
      //stop ()
    //endif
    hv_colI = HTuple(hv_ColI[hv_i]);
    hv_rowI = HTuple(hv_RowI[hv_i]);

    hv_kb = hv_ki-hv_isz;
    if (0 != (hv_kb<0))
    {
      hv_kb = hv_nG+hv_kb;
    }
    hv_ke = (hv_ki+hv_isz)-1;
    if (0 != (hv_ke>=hv_nG))
    {
      hv_ke = hv_ke-hv_nG;
    }

    if (0 != (hv_kb<=hv_ke))
    {
      hv_ColGs = hv_ColG.TupleSelectRange(hv_kb,hv_ke);
      hv_RowGs = hv_RowG.TupleSelectRange(hv_kb,hv_ke);
      hv_K = HTuple::TupleGenSequence(hv_kb,hv_ke,1);
    }
    else
    {
      hv_ColGs.Clear();
      hv_ColGs.Append(hv_ColG.TupleSelectRange(0,hv_ke));
      hv_ColGs.Append(hv_ColG.TupleSelectRange(hv_kb,hv_nG-1));
      hv_RowGs.Clear();
      hv_RowGs.Append(hv_RowG.TupleSelectRange(0,hv_ke));
      hv_RowGs.Append(hv_RowG.TupleSelectRange(hv_kb,hv_nG-1));
      hv_K.Clear();
      hv_K.Append(HTuple::TupleGenSequence(0,hv_ke,1));
      hv_K.Append(HTuple::TupleGenSequence(hv_kb,hv_nG-1,1));
      hv_num = hv_RowGs.TupleLength();
      //DIGcs := DIGcOut[kb:nG-1]
    }

    //* CircularSector (21, 1601, 0, K1)
    //***** ????? ****
    //ColGs := ColG
    //RowGs := RowG
    //***** ????? ****
    hv_DIGcOut = hv_ColGs-hv_colI;
    hv_DIGr = hv_RowGs-hv_rowI;
    hv_DIGs = ((hv_DIGcOut*hv_DIGcOut)+(hv_DIGr*hv_DIGr)).TupleSqrt();
    //DIG := DIGcOut+DIGr
    //* tuple_min_ind (DIGs, minD, k)
    TupleSortIndex(hv_DIGs, &hv_IndicesD);

    TupleMin(hv_DIGs, &hv_minD);
    //stop ()

    hv_k = ((const HTuple&)hv_IndicesD)[0];
    hv_ki = HTuple(hv_K[hv_k]);
    hv_rowG = HTuple(hv_RowG[hv_ki]);
    hv_colG = HTuple(hv_ColG[hv_ki]);
    //gen_region_points (PGs, RowG, ColG)

    //distance_pp (rowG, colG, rowI, colI, Distance)
    hv_ki1 = hv_ki-1;
    if (0 != (hv_ki1<0))
    {
      hv_ki1 = hv_nG+hv_ki1;
    }
    hv_colG1 = HTuple(hv_ColG[hv_ki1]);
    hv_rowG1 = HTuple(hv_RowG[hv_ki1]);
    hv_ki2 = hv_ki+1;
    if (0 != (hv_ki2>=hv_nG))
    {
      hv_ki2 = (-hv_nG)+hv_ki2;
    }
    hv_colG2 = HTuple(hv_ColG[hv_ki2]);
    hv_rowG2 = HTuple(hv_RowG[hv_ki2]);

    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"red");
    GenCrossContourXld(&ho_CI, hv_rowI, hv_colI, 0.25, 6);
    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"blue");
    GenCrossContourXld(&ho_CG, hv_rowG, hv_colG, 0.15, 6);
    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"cyan");
    GenCrossContourXld(&ho_CG1, hv_rowG1, hv_colG1, 0.1, 6);
    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"blue violet");
    GenCrossContourXld(&ho_CG2, hv_rowG2, hv_colG2, 0.2, 6);

    DistPointToLineSegmH(hv_rowI, hv_colI, hv_rowG, hv_colG, hv_rowG1, hv_colG1, &hv_d1, 
        &hv_rowm1, &hv_colGm1, &hv_t1);
    DistPointToLineSegmH(hv_rowI, hv_colI, hv_rowG, hv_colG, hv_rowG2, hv_colG2, &hv_d2, 
        &hv_rowm2, &hv_colGm2, &hv_t2);
    hv_d = hv_d1.TupleMin2(hv_d2);
    hv_dd = hv_d;
    if (0 != (HTuple(HTuple(hv_t1<0).TupleAnd(hv_t2<0)).TupleOr(HTuple(hv_t1>1).TupleAnd(hv_t2>1))))
    {
      hv_kim2 = hv_ki-2;
      if (0 != (hv_kim2<0))
      {
        hv_kim2 = hv_nG+hv_kim2;
      }
      hv_colGm1 = HTuple(hv_ColG[hv_kim2]);
      hv_rowGm1 = HTuple(hv_RowG[hv_kim2]);
      DistPointToLineSegmH(hv_rowI, hv_colI, hv_rowGm1, hv_colGm1, hv_rowG1, hv_colG1, 
          &hv_dm1, &hv_rowGm1, &hv_colGm1, &hv_tm1);
      //dev_set_color ('dark turquoise')
      //gen_cross_contour_xld (CG2, rowGm1, colGm1, 0.07, 6)
      if (0 != (HTuple(hv_tm1<0).TupleOr(hv_tm1>1)))
      {
        hv_kip2 = hv_ki+2;
        if (0 != (hv_kip2>=hv_nG))
        {
          hv_kip2 = (-hv_nG)+hv_kip2;
        }
        hv_colGp2 = HTuple(hv_ColG[hv_kip2]);
        hv_rowGp2 = HTuple(hv_RowG[hv_kip2]);
        //dev_set_color ('steel blue')
        //gen_cross_contour_xld (CG2, rowGp2, colGp2, 0.23, 6)
        DistPointToLineSegmH(hv_rowI, hv_colI, hv_rowG2, hv_colG2, hv_rowGp2, hv_colGp2, 
            &hv_dp2, &hv_rowGp2, &hv_colGp2, &hv_tp2);
        hv_dd = hv_dp2;
      }
      else
      {
        hv_dd = hv_dm1;
      }
    }
    hv_d = hv_d.TupleMin2(hv_dd);
    //d := DIG[k]
    //D[i] := minD
    (*hv_D)[hv_i] = hv_d;
    //distance_pp (rowI, colI, rowG, colG, d1)
  }
  }
  return;
}

void DistPointToLineSegmH (HTuple hv_y, HTuple hv_x, HTuple hv_y1, HTuple hv_x1, HTuple hv_y2, 
    HTuple hv_x2, HTuple *hv_distance, HTuple *hv_ym, HTuple *hv_xm, HTuple *hv_t)
{

  // Local iconic variables

  // Local control variables
  HTuple  hv_td;

  hv_td = ((hv_x2-hv_x1)*(hv_x2-hv_x1))+((hv_y2-hv_y1)*(hv_y2-hv_y1));
  if (0 != (hv_td!=0.0))
  {
    (*hv_t) = (((hv_x-hv_x1)*(hv_x2-hv_x1))+((hv_y-hv_y1)*(hv_y2-hv_y1)))/hv_td;
  }
  else
  {
    (*hv_t) = 111;
  }

  if (0 != ((*hv_t)>=1.))
  {
    //distance := sqrt((x - x2)*(x - x2) + (y - y2)*(y - y2))
    (*hv_xm) = hv_x2;
    (*hv_ym) = hv_y2;
  }
  else if (0 != ((*hv_t)<=0.))
  {
    (*hv_xm) = hv_x1;
    (*hv_ym) = hv_y1;
    //distance := sqrt((x - x1)*(x - x1) + (y - y1)*(y - y1))
  }
  else
  {
    (*hv_xm) = hv_x1+((*hv_t)*(hv_x2-hv_x1));
    (*hv_ym) = hv_y1+((*hv_t)*(hv_y2-hv_y1));
  }
  (*hv_distance) = (((hv_x-(*hv_xm))*(hv_x-(*hv_xm)))+((hv_y-(*hv_ym))*(hv_y-(*hv_ym)))).TupleSqrt();
  return;
}

void MoveContourH (HObject ho_Contour, HObject *ho_ContourOut, HTuple hv_mr, HTuple hv_mc)
{

  // Local iconic variables

  // Local control variables
  HTuple  hv_Row, hv_Col, hv_Rowout, hv_Colout;

  GetContourXld(ho_Contour, &hv_Row, &hv_Col);
  hv_Rowout = hv_Row+hv_mr;
  hv_Colout = hv_Col+hv_mc;
  GenContourPolygonXld(&(*ho_ContourOut), hv_Rowout, hv_Colout);
  return;
}

void Region_Threshold_SubPixH (HObject ho_RegSel, HObject ho_Im, HTuple hv_Thr, HTuple *hv_RowsSub, 
    HTuple *hv_ColsSub)
{

  // Local iconic variables
  HObject  ho_Cross;

  // Local control variables
  HTuple  hv_Pos_Sub, hv_Im_H, hv_Im_W, hv_Rows;
  HTuple  hv_Cols, hv_Cont_Len, hv_Pos, hv_Gray0, hv_Hole;
  HTuple  hv_Pos_Next, hv_Pos_Prev, hv_Row_Prev, hv_Col_Prev;
  HTuple  hv_Row_Next, hv_Col_Next, hv_Row_Curr, hv_Col_Curr;
  HTuple  hv_Down, hv_Left, hv_Gray1, hv_Gray2, hv_X0, hv_X1;
  HTuple  hv_X2, hv_Xr1, hv_Y1, hv_Y2, hv_Yr1, hv_Yr2, hv_Xr2;

  (*hv_RowsSub) = HTuple();
  (*hv_ColsSub) = HTuple();
  hv_Pos_Sub = 0;

  GetImageSize(ho_Im, &hv_Im_H, &hv_Im_W);
  GetRegionContour(ho_RegSel, &hv_Rows, &hv_Cols);
  TupleLength(hv_Rows, &hv_Cont_Len);

  //???? ?? ?????
  {
  HTuple end_val9 = hv_Cont_Len-1;
  HTuple step_val9 = 1;
  for (hv_Pos=0; hv_Pos.Continue(end_val9, step_val9); hv_Pos += step_val9)
  {
    GetGrayval(ho_Im, HTuple(hv_Rows[hv_Pos]), HTuple(hv_Cols[hv_Pos]), &hv_Gray0);

    if (0 != (hv_Gray0<hv_Thr))
    {
      hv_Hole = 1;
      break;
    }
    else if (0 != (hv_Gray0>hv_Thr))
    {
      hv_Hole = 0;
      break;
    }

  }
  }


  {
  HTuple end_val23 = hv_Cont_Len-1;
  HTuple step_val23 = 1;
  for (hv_Pos=0; hv_Pos.Continue(end_val23, step_val23); hv_Pos += step_val23)
  {
    GetGrayval(ho_Im, HTuple(hv_Rows[hv_Pos]), HTuple(hv_Cols[hv_Pos]), &hv_Gray0);

    hv_Pos_Next = hv_Pos+1;
    if (0 != (hv_Pos_Next>(hv_Cont_Len-1)))
    {
      hv_Pos_Next = 0;
    }
    hv_Pos_Prev = hv_Pos-1;
    if (0 != (hv_Pos_Prev<0))
    {
      hv_Pos_Prev = hv_Cont_Len-1;
    }
    hv_Row_Prev = HTuple(hv_Rows[hv_Pos_Prev]);
    hv_Col_Prev = HTuple(hv_Cols[hv_Pos_Prev]);
    hv_Row_Next = HTuple(hv_Rows[hv_Pos_Next]);
    hv_Col_Next = HTuple(hv_Cols[hv_Pos_Next]);
    hv_Row_Curr = HTuple(hv_Rows[hv_Pos]);
    hv_Col_Curr = HTuple(hv_Cols[hv_Pos]);

    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"red");
    GenCrossContourXld(&ho_Cross, hv_Row_Curr, hv_Col_Curr, 1, 0);


    if (0 != (HTuple(HTuple(HTuple(hv_Row_Curr>=(hv_Im_H-1)).TupleOr(hv_Col_Curr>=(hv_Im_W-1))).TupleOr(hv_Row_Curr==0)).TupleOr(hv_Col_Curr==0)))
    {
      continue;
    }

    //???????????
    if (0 != (HTuple(hv_Row_Curr>hv_Row_Prev).TupleOr(hv_Row_Curr<hv_Row_Next)))
    {
      hv_Down = 1;
    }
    else
    {
      hv_Down = 0;
    }

    if (0 != (HTuple(hv_Col_Curr<hv_Col_Prev).TupleOr(hv_Col_Curr>hv_Col_Next)))
    {
      hv_Left = 1;
    }
    else
    {
      hv_Left = 0;
    }

    //-- Cols -------------------------------------------
    GetGrayval(ho_Im, hv_Row_Curr, hv_Col_Curr+1, &hv_Gray1);
    GetGrayval(ho_Im, hv_Row_Curr, hv_Col_Curr-1, &hv_Gray2);
    hv_X0 = -1;
    hv_X1 = 0;
    hv_X2 = 0;
    hv_Xr1 = -1;

    //???? ????. ?????????? ? ????? ??????
    if (0 != (hv_Down.TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray1>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray1<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray0;
      hv_X2 = hv_Gray1;
      hv_Y1 = HTuple(hv_Cols[hv_Pos]);
      hv_Y2 = HTuple(hv_Cols[hv_Pos])+1;
      //???? ?????. ?????????? ? ????? ?????
    }
    else if (0 != (HTuple(hv_Down.TupleNot()).TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray2>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray2<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray2;
      hv_X2 = hv_Gray0;
      hv_Y1 = HTuple(hv_Cols[hv_Pos])-1;
      hv_Y2 = HTuple(hv_Cols[hv_Pos]);
    }

    if (0 != (HTuple(hv_X0>=0).TupleAnd(hv_X2!=hv_X1)))
    {
      hv_Xr1 = (hv_Y1.TupleReal())+((((hv_X0-hv_X1).TupleReal())*((hv_Y2-hv_Y1).TupleReal()))/((hv_X2-hv_X1).TupleReal()));
      hv_Yr1 = HTuple(hv_Rows[hv_Pos]);

      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),"green");
      GenCrossContourXld(&ho_Cross, hv_Yr1, hv_Xr1, 0.5, 0);
    }

    //--- Rows -------------------------------------------
    GetGrayval(ho_Im, hv_Row_Curr+1, hv_Col_Curr, &hv_Gray1);
    GetGrayval(ho_Im, hv_Row_Curr-1, hv_Col_Curr, &hv_Gray2);
    hv_X0 = -1;
    hv_Yr2 = -1;

    //???? ?????. ?????????? ? ????? ?????
    if (0 != (hv_Left.TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray1>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray1<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray0;
      hv_X2 = hv_Gray1;
      hv_Y1 = HTuple(hv_Rows[hv_Pos]);
      hv_Y2 = HTuple(hv_Rows[hv_Pos])+1;
      //???? ??????. ?????????? ? ????? ??????
    }
    else if (0 != (HTuple(hv_Left.TupleNot()).TupleAnd(HTuple(HTuple(hv_Hole==1).TupleAnd(hv_Gray2>hv_Thr)).TupleOr(HTuple(hv_Hole==0).TupleAnd(hv_Gray2<hv_Thr)))))
    {
      hv_X0 = hv_Thr;
      hv_X1 = hv_Gray2;
      hv_X2 = hv_Gray0;
      hv_Y1 = HTuple(hv_Rows[hv_Pos])-1;
      hv_Y2 = HTuple(hv_Rows[hv_Pos]);
    }

    if (0 != (HTuple(hv_X0>=0).TupleAnd(hv_X2!=hv_X1)))
    {
      hv_Yr2 = (hv_Y1.TupleReal())+((((hv_X0-hv_X1).TupleReal())*((hv_Y2-hv_Y1).TupleReal()))/((hv_X2-hv_X1).TupleReal()));
      hv_Xr2 = HTuple(hv_Cols[hv_Pos]);

      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),"red");
      GenCrossContourXld(&ho_Cross, hv_Yr2, hv_Xr2, 0.5, 0);
    }



    if (0 != (HTuple(hv_Xr1>=0).TupleAnd(hv_Yr2>=0)))
    {
      if (0 != (hv_Xr1>hv_Xr2))
      {
        if (0 != (hv_Yr1>hv_Yr2))
        {
          //Yr_Avg := (Yr2 + Yr1) / 2
          //Xr_Avg := (Xr2 + Xr1) / 2

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;
        }
        else
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;
        }
      }
      else
      {
        if (0 != (hv_Yr1<hv_Yr2))
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;
        }
        else
        {
          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
          hv_Pos_Sub += 1;

          (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
          (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
          hv_Pos_Sub += 1;
        }
      }
    }
    else if (0 != (hv_Xr1>=0))
    {
      (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr1;
      (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr1;
      hv_Pos_Sub += 1;
    }
    else if (0 != (hv_Yr2>=0))
    {
      (*hv_RowsSub)[hv_Pos_Sub] = hv_Yr2;
      (*hv_ColsSub)[hv_Pos_Sub] = hv_Xr2;
      hv_Pos_Sub += 1;
    }

  }
  }
  return;
}

void ReverseContourH (HObject ho_ContourIn, HObject *ho_ContourOut)
{

  // Local iconic variables
  HObject  ho_ContourGrsmi;

  // Local control variables
  HTuple  hv_RowGrsm, hv_ColGrsm, hv_RowGrsmi, hv_ColGrsmi;

  (*ho_ContourOut) = ho_ContourIn;
  GetContourXld((*ho_ContourOut), &hv_RowGrsm, &hv_ColGrsm);
  TupleInverse(hv_RowGrsm, &hv_RowGrsmi);
  TupleInverse(hv_ColGrsm, &hv_ColGrsmi);
  GenContourPolygonXld(&ho_ContourGrsmi, hv_RowGrsmi, hv_ColGrsmi);
  //area_center_xld (ContourGrsmi, AreaCGR, Row9, Column9, PointOrderCGr)
  (*ho_ContourOut) = ho_ContourGrsmi;
  return;
}

void MeasureDisplacementH (HObject ho_Im, HObject ho_RegionInoD, HObject ho_MeanderRects, 
    HObject ho_RegionsGrMe, HObject ho_ContourGrsm, HTuple hv_meander, HTuple hv_thr, 
    HTuple hv_RowGsm, HTuple hv_ColGsm, HTuple *hv_Displacement)
{

  // Local iconic variables
  HObject  ho_MeanderRect, ho_RegionIR, ho_RegionsIR;
  HObject  ho_ContourIK, ho_ContourGrsma;

  // Local control variables
  HTuple  hv_AreaIR, hv_Row, hv_Column, hv_Indices;
  HTuple  hv_Inverted, hv_RowsSubI, hv_ColsSubI, hv_AreaIK;
  HTuple  hv_RowIK, hv_ColIK, hv_PointOrderIK, hv_mr, hv_mc;
  HTuple  hv_RowI, hv_ColI, hv_RowG, hv_ColG, hv_nI, hv_isz;
  HTuple  hv_DistIG, hv_IsInside, hv_Sign;

  //MeasureDisplacement() - 07.09.2925

  SelectObj(ho_MeanderRects, &ho_MeanderRect, hv_meander);
  //union1 (RegionsGrMe, RegionGrMe)
  Intersection(ho_RegionInoD, ho_MeanderRect, &ho_RegionIR);
  Connection(ho_RegionIR, &ho_RegionsIR);
  AreaCenter(ho_RegionsIR, &hv_AreaIR, &hv_Row, &hv_Column);
  TupleSortIndex(hv_AreaIR, &hv_Indices);
  TupleInverse(hv_Indices, &hv_Inverted);
  SelectObj(ho_RegionsIR, &ho_RegionIR, HTuple(hv_Inverted[0])+1);

  Region_Threshold_SubPixH(ho_RegionIR, ho_Im, hv_thr, &hv_RowsSubI, &hv_ColsSubI);
  GenContourPolygonXld(&ho_ContourIK, hv_RowsSubI, hv_ColsSubI);
  AreaCenterXld(ho_ContourIK, &hv_AreaIK, &hv_RowIK, &hv_ColIK, &hv_PointOrderIK);
  if (0 != (hv_PointOrderIK==HTuple("negative")))
  {
    ReverseContourH(ho_ContourIK, &ho_ContourIK);
    //area_center_xld (ContourIK, Area, RowBcl, ColBcl, PointOrderB1)
    //nrev := nrev+1
  }

  //RowGsm := RowGsm[meander-1]
  //ColGsm := ColGsm[meander-1]

  hv_mr = hv_RowIK-hv_RowGsm;
  hv_mc = hv_ColIK-hv_ColGsm;

  //* moving the contour
  //mr := mr+2
  MoveContourH(ho_ContourGrsm, &ho_ContourGrsma, hv_mr, hv_mc);

  GetContourXld(ho_ContourIK, &hv_RowI, &hv_ColI);
  GetContourXld(ho_ContourGrsma, &hv_RowG, &hv_ColG);
  TupleLength(hv_RowI, &hv_nI);
  hv_isz = 21;
  DistanceContours2H(hv_RowI, hv_ColI, hv_RowG, hv_ColG, hv_isz, &hv_DistIG);

  //stop ()
  //** signed displacement
  TestXldPoint(ho_ContourGrsma, hv_RowI, hv_ColI, &hv_IsInside);

  //gen_contour_polygon_xld (Line, [0,RowI], [0,ColI])
  //intersection_contours_xld (Line, ContourIK, 'all', Row1, Column1, IsOverlapping)
  //intersection_line_contour_xld (ContourIK, 0, RowI, 0, ColI, Row1, Column1, IsOverlapping)
  hv_Sign = (hv_IsInside*2.0)-1.0;
  (*hv_Displacement) = (-hv_Sign)*hv_DistIG;
  return;
}


