/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 18.11
 * Usage: Interface to C
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef __APPLE__
#  include "HalconC.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONC/HalconC.h>
#  else
#    include <HALCONCxl/HalconC.h>
#  endif
#endif


extern HUserImport HINT HFilt_AMM_04GetOffset();

HINT offset = -1;

Herror HcPreCallUser(HINT proc_index_local, Hproc_handle *proc_handle)
{
  Hproc_handle ph;
  Herror err;
  if (offset < 0)
  {
    /* First use of this extension package, query my offset */
    offset = HFilt_AMM_04GetOffset();
    if (offset < 0)
    {
      /* HALCON libary not initialized (extension package as first usage). */
      /* Trigger initialization by touching system operator and try again. */
      err = HcPreCall(0,&ph);
      err = HcPostCall(ph,H_MSG_OK);
      offset = HFilt_AMM_04GetOffset();
      if (offset < 0)
      {
        /* Ok, so something is *really* wrong */
        *proc_handle = NULL;
        return H_ERR_UEXTNI;
      }
    }
  }
  return HcPreCall(offset + proc_index_local, proc_handle);
}

HUserExport Herror T_user_Filt_AMM_04(const Htuple hv_Input, const Htuple hv_Win_Len, const Htuple hv_Move_Avg, const Htuple hv_thrMB, const Htuple hv_thrSP, Htuple *hv_Tuple_Avg_CMax, Htuple *hv_Tuple_Avg_CMin, Htuple *hv_Tuple_Avg_MM_Th)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&hv_Input);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&hv_Win_Len);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&hv_Move_Avg);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&hv_thrMB);
  if (err == H_MSG_OK) err = HcStoreICT(ph,4,&hv_thrSP);
  if (err == H_MSG_OK) err = HcCall(ph);
  err = HcStoreOCT(ph,0,hv_Tuple_Avg_CMax,err);
  err = HcStoreOCT(ph,1,hv_Tuple_Avg_CMin,err);
  err = HcStoreOCT(ph,2,hv_Tuple_Avg_MM_Th,err);
  return HcPostCall(ph,err);
}

HUserExport Herror user_Filt_AMM_04(double hv_Input, double hv_Win_Len, double hv_Move_Avg, double hv_thrMB, double hv_thrSP, double *hv_Tuple_Avg_CMax, double *hv_Tuple_Avg_CMin, double *hv_Tuple_Avg_MM_Th)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) err = HcStoreICD(ph,0,hv_Input);
  if (err == H_MSG_OK) err = HcStoreICD(ph,1,hv_Win_Len);
  if (err == H_MSG_OK) err = HcStoreICD(ph,2,hv_Move_Avg);
  if (err == H_MSG_OK) err = HcStoreICD(ph,3,hv_thrMB);
  if (err == H_MSG_OK) err = HcStoreICD(ph,4,hv_thrSP);
  if (err == H_MSG_OK) err = HcCall(ph);
  err = HcStoreOCD(ph,0,hv_Tuple_Avg_CMax,err);
  err = HcStoreOCD(ph,1,hv_Tuple_Avg_CMin,err);
  err = HcStoreOCD(ph,2,hv_Tuple_Avg_MM_Th,err);
  return HcPostCall(ph,err);
}

