/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 18.11
 * Usage: Initialization of operator table
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef __APPLE__
#  include "Halcon.h"
#  include "HCtype.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCON/Halcon.h>
#    include <HALCON/HCtype.h>
#  else
#    include <HALCONxl/Halcon.h>
#    include <HALCONxl/HCtype.h>
#  endif
#endif

Herror CIPUserFilt_AMM_04(Hproc_handle proc_id);



static Herror HSystem0(INT4 xid)
{
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_ParameterType,0,"Fffff"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_ParameterType,1,"fff"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumInpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumOutpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumInpCtrlPar,5));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumOutpCtrlPar,3));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_LogicalName,"user_Filt_AMM_04"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_PhysicalName,"CIPUserFilt_AMM_04"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_procedure,CIPUserFilt_AMM_04));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_module,1ul));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_process_excl_local,HAG_PAR_NO_RESTRICT));
#ifndef HC_NO_COMPUTE_DEVICES
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_compute_device,0));
#endif
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelization,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_aopCost,NULL));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_numCost,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelMinCosts,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelRegionsplit,0));

return H_MSG_OK;
}
/******************************/



HINT m_offset = -1;

extern HUserExport HINT HFilt_AMM_04GetOffset()
{
  return m_offset;
}


HUserExport Herror HXPkgInit(INT4 xpkg_id)
{

  INT4 osid;
  HCkP(HXPkgOpenId( xpkg_id, HALCON_VERSION_CODE,H_OPERATOR_INFO_DERIVATE,1,&osid));
  m_offset = osid;

  HCkP(HSystem0(xpkg_id));
  return H_MSG_OK;
}
