/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 13.0
 * Usage: Interface to C
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#if defined(__cplusplus)
extern "C" {
#endif

HUserExport Herror T_user_Filt_AMM_04(const Htuple hv_Input, const Htuple hv_Win_Len, const Htuple hv_Move_Avg, const Htuple hv_thrMB, const Htuple hv_thrSP, Htuple *hv_Tuple_Avg_CMax, Htuple *hv_Tuple_Avg_CMin, Htuple *hv_Tuple_Avg_MM_Th);
HUserExport Herror user_Filt_AMM_04(double hv_Input, double hv_Win_Len, double hv_Move_Avg, double hv_thrMB, double hv_thrSP, double *hv_Tuple_Avg_CMax, double *hv_Tuple_Avg_CMin, double *hv_Tuple_Avg_MM_Th);


#if defined(__cplusplus)
}
#endif

