/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 13.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HFILTAMM04
#define HCPP_HFILTAMM04

namespace HalconCpp
{




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

// Medial filter
HUserExport void UserFiltAMM04(const HTuple& hv_Input, const HTuple& hv_Win_Len, const HTuple& hv_Move_Avg, const HTuple& hv_thrMB, const HTuple& hv_thrSP, HTuple* hv_Tuple_Avg_CMax, HTuple* hv_Tuple_Avg_CMin, HTuple* hv_Tuple_Avg_MM_Th);

}

#endif
