///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 18.11.0.1
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp949).
// Ensure that the interface encoding is set to locale encoding by calling
// SetHcppInterfaceStringEncodingIsUtf8(false) at the beginning of the program.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#  if defined(__linux__) && (defined(__i386__) || defined(__x86_64__)) \
                         && !defined(NO_EXPORT_APP_MAIN)
#    include <X11/Xlib.h>
#  endif
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#  include <stdio.h>
#  include <HALCON/HpThread.h>
#  include <CoreFoundation/CFRunLoop.h>
#endif



using namespace HalconCpp;

// Procedure declarations 
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ();

// Procedures 
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ()
{

  //This procedure sets different update settings to 'off'.
  //This is useful to get the best performance and reduce overhead.
  //
  // dev_update_pc(...); only in hdevelop
  // dev_update_var(...); only in hdevelop
  // dev_update_window(...); only in hdevelop
  return;
}

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local iconic variables
  HObject  ho_Img_Im, ho_Reg_Im, ho_Reg_Im_CON;
  HObject  ho_REG_Eyes, ho_REG_Eyes_UN, ho_Reg_Im_CON_CLS;
  HObject  ho_REG_DIFF, ho_Reg_Im_CON1;

  // Local control variables
  HTuple  hv_path, hv_time_0, hv_time_1, hv_time_S;

  dev_update_off();
  hv_path = "C:/Work/Data/Scratch & Other/Scratch/";
  ReadImage(&ho_Img_Im, hv_path+"Im.tif");
  // stop(...); only in hdevelop

  CountSeconds(&hv_time_0);

  Threshold(ho_Img_Im, &ho_Reg_Im, 240, 255);
  //threshold (Img_Im, Reg_Im, 190, 230)

  //complement (Reg_Im, Reg_Im_INV)
  //dilation_circle (Reg_Im_INV, Reg_Im_DIL, 1.5)


  //paint_region (Reg_Im_INV, Img_Im, Img_Im_PRT, 200, 'fill')
  //threshold (Img_Im, Reg_Im, 240, 255)


  Connection(ho_Reg_Im, &ho_Reg_Im_CON);
  SelectShape(ho_Reg_Im_CON, &ho_REG_Eyes, "area", "or", 1000, 100000);
  Union1(ho_REG_Eyes, &ho_REG_Eyes_UN);

  //* select_shape(Reg_Im_CON, REG_Eyes, 'area', 'or',  60, 3000)
  //complement (REG_Eyes, REG_Eyes_INV)
  //closing_circle (REG_Eyes, Reg_Im_CON_CLS, 3.5)
  //difference (Reg_Im_CON_CLS, REG_Eyes, REG_DIFF)


  //dilation_circle (Reg_Im, Reg_Im_DIL, 3.5)
  //erosion_circle (Reg_Im_DIL, Reg_Im_CON_CLS, 3.5)
  ClosingCircle(ho_REG_Eyes_UN, &ho_Reg_Im_CON_CLS, 3.5);

  Difference(ho_Reg_Im_CON_CLS, ho_REG_Eyes_UN, &ho_REG_DIFF);

  Connection(ho_REG_DIFF, &ho_Reg_Im_CON1);
  SelectShape(ho_Reg_Im_CON1, &ho_REG_Eyes, "struct_factor", "or", 12, 300);
  SelectShape(ho_REG_Eyes, &ho_REG_Eyes, "contlength", "or", 30, 300);

  CountSeconds(&hv_time_1);
  hv_time_S = hv_time_1-hv_time_0;

  //union1 (REG_Eyes, REG_Eyes_UN)
  //* dilation_circle(REG_Eyes_UN, REG_Eyes_UN_DIL, 100.5)
  //* erosion_circle(REG_Eyes_UN_DIL, REG_Eyes_UN_ER, 80.5)



  // stop(...); only in hdevelop

}


#ifndef NO_EXPORT_APP_MAIN

#ifdef __APPLE__
// On OS X systems, we must have a CFRunLoop running on the main thread in
// order for the HALCON graphics operators to work correctly, and run the
// action function in a separate thread. A CFRunLoopTimer is used to make sure
// the action function is not called before the CFRunLoop is running.
// Note that starting with macOS 10.12, the run loop may be stopped when a
// window is closed, so we need to put the call to CFRunLoopRun() into a loop
// of its own.
HTuple      gStartMutex;
H_pthread_t gActionThread;
HBOOL       gTerminate = FALSE;

static void timer_callback(CFRunLoopTimerRef timer, void *info)
{
  UnlockMutex(gStartMutex);
}

static Herror apple_action(void **parameters)
{
  // Wait until the timer has fired to start processing.
  LockMutex(gStartMutex);
  UnlockMutex(gStartMutex);

  try
  {
    action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
  }

  // Tell the main thread to terminate itself.
  LockMutex(gStartMutex);
  gTerminate = TRUE;
  UnlockMutex(gStartMutex);
  CFRunLoopStop(CFRunLoopGetMain());
  return H_MSG_OK;
}

static int apple_main(int argc, char *argv[])
{
  Herror                error;
  CFRunLoopTimerRef     Timer;
  CFRunLoopTimerContext TimerContext = { 0, 0, 0, 0, 0 };

  CreateMutex("type","sleep",&gStartMutex);
  LockMutex(gStartMutex);

  error = HpThreadHandleAlloc(&gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleAlloc failed: %d\n", error);
    exit(1);
  }

  error = HpThreadCreate(gActionThread,0,apple_action);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadCreate failed: %d\n", error);
    exit(1);
  }

  Timer = CFRunLoopTimerCreate(kCFAllocatorDefault,
                               CFAbsoluteTimeGetCurrent(),0,0,0,
                               timer_callback,&TimerContext);
  if (!Timer)
  {
    fprintf(stderr,"CFRunLoopTimerCreate failed\n");
    exit(1);
  }
  CFRunLoopAddTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);

  for (;;)
  {
    HBOOL terminate;

    CFRunLoopRun();

    LockMutex(gStartMutex);
    terminate = gTerminate;
    UnlockMutex(gStartMutex);

    if (terminate)
      break;
  }

  CFRunLoopRemoveTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);
  CFRelease(Timer);

  error = HpThreadHandleFree(gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleFree failed: %d\n", error);
    exit(1);
  }

  ClearMutex(gStartMutex);
  return 0;
}
#endif

int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#elif defined(__linux__) && (defined(__i386__) || defined(__x86_64__))
    XInitThreads();
#endif

    // file was stored with local-8-bit encoding
    //   -> set the interface encoding accordingly
    SetHcppInterfaceStringEncodingIsUtf8(false);

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

#ifndef __APPLE__
    action();
#else
    ret = apple_main(argc,argv);
#endif
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
    ret = 1;
  }
  return ret;
}

#endif


#endif


