///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 18.11.0.1
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp949).
// Ensure that the interface encoding is set to locale encoding by calling
// SetHcppInterfaceStringEncodingIsUtf8(false) at the beginning of the program.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#  if defined(__linux__) && (defined(__i386__) || defined(__x86_64__)) \
                         && !defined(NO_EXPORT_APP_MAIN)
#    include <X11/Xlib.h>
#  endif
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#  include <stdio.h>
#  include <HALCON/HpThread.h>
#  include <CoreFoundation/CFRunLoop.h>
#endif



using namespace HalconCpp;

// Procedure declarations 
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ();

// Procedures 
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ()
{

  //This procedure sets different update settings to 'off'.
  //This is useful to get the best performance and reduce overhead.
  //
  // dev_update_pc(...); only in hdevelop
  // dev_update_var(...); only in hdevelop
  // dev_update_window(...); only in hdevelop
  return;
}

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local iconic variables
  HObject  ho_Img_Im, ho_Reg_Im_0, ho_Reg_Im, ho_Reg_Im_ER;
  HObject  ho_Reg_Im_CON, ho_REG_Eyes2, ho_REG_Eyes3, ho_ERec;
  HObject  ho_Region1, ho_Region1_DIL;

  // Local control variables
  HTuple  hv_path, hv_path1, hv_path2, hv_rec_row;
  HTuple  hv_rec_col, hv_rec_phi, hv_Length1, hv_Length2;
  HTuple  hv_line_row1, hv_line_col1, hv_line_row2, hv_line_col2;
  HTuple  hv_line_col, hv_rec_len, hv_pos, hv_cur_phi, hv_cur_y;
  HTuple  hv_cur_x, hv_count_obj, hv_i, hv_phi, hv_d_phi;
  HTuple  hv_d_phi1, hv_powY, hv_powX, hv_dist_XY;

  dev_update_off();
  hv_path = "C:/Work/Data/Scratch & Other/Scratch/";
  hv_path1 = "C:/Work/Data/Scratch & Other/249/";
  hv_path2 = "C:/Work/Data/Scratch & Other/110/";

  ReadImage(&ho_Img_Im, hv_path1+"Im.tif");

  //read_image (Img_Im, path1 + 'Im.tif')
  //stop ()


  //** ------------ Search preliminary ------------------
  Threshold(ho_Img_Im, &ho_Reg_Im_0, 100, 255);

  Threshold(ho_Img_Im, &ho_Reg_Im, 252, 255);
  //closing_circle (Reg_Im, Reg_Im_ER, 1.1)
  //dilation_circle (Reg_Im_ER, Reg_Im_ER, 1.5)
  ErosionCircle(ho_Reg_Im, &ho_Reg_Im_ER, 1.1);

  Connection(ho_Reg_Im_ER, &ho_Reg_Im_CON);
  //select_shape (Reg_Im_CON, Reg_Im_CON, 'area', 'or', 6, 100000)
  //select_shape (Reg_Im_CON, REG_Eyes1, 'struct_factor', 'or', 6, 3000)
  SelectShape(ho_Reg_Im_CON, &ho_REG_Eyes2, "area", "or", 16, 100000);
  SelectShape(ho_REG_Eyes2, &ho_REG_Eyes3, "struct_factor", "or", 12, 300);

  SelectShape(ho_REG_Eyes3, &ho_REG_Eyes3, (HTuple("rectangularity").Append("ra")), 
      "and", (HTuple(0.3).Append(15)), (HTuple(1.0).Append(1500)));


  // stop(...); only in hdevelop
  //skeleton (REG_Eyes3, Skeleton)

  //* pruning(Skeleton, RegionPrune, 3)
  //* gen_contours_skeleton_xld(RegionPrune, Contours, 1, 'filter')
  //* select_contours_xld(Contours, SelectedContours, 'contour_length', 5., 200., -0.5, 0.5)
  //** ------------ Search for objects on the same line -----------
  //--- We go through all the objects of the regions and look for those that lie on the same line
  SmallestRectangle2(ho_REG_Eyes3, &hv_rec_row, &hv_rec_col, &hv_rec_phi, &hv_Length1, 
      &hv_Length2);
  GenRectangle2(&ho_ERec, hv_rec_row, hv_rec_col, hv_rec_phi, hv_Length1, hv_Length2);
  if (HDevWindowStack::IsOpen())
    SetDraw(HDevWindowStack::GetActive(),"margin");
  if (HDevWindowStack::IsOpen())
    SetLineWidth(HDevWindowStack::GetActive(),6);
  if (HDevWindowStack::IsOpen())
    SetColor(HDevWindowStack::GetActive(),"blue");
  if (HDevWindowStack::IsOpen())
    DispObj(ho_Img_Im, HDevWindowStack::GetActive());
  //dev_display (ERec)


  hv_line_row1 = HTuple();
  hv_line_col1 = HTuple();
  hv_line_row2 = HTuple();
  hv_line_col2 = HTuple();

  //- For all objects found
  //Number of found lines
  hv_line_col = 0;
  TupleLength(hv_rec_phi, &hv_rec_len);
  hv_pos = 0;
  while (0 != (hv_pos<(hv_rec_len-1)))
  {

    hv_cur_phi = HTuple(hv_rec_phi[hv_pos]);
    hv_cur_y = HTuple(hv_rec_row[hv_pos]);
    hv_cur_x = HTuple(hv_rec_col[hv_pos]);

    //Coordinate initialization
    TupleConcat(hv_line_row1, hv_cur_y, &hv_line_row1);
    TupleConcat(hv_line_col1, hv_cur_x, &hv_line_col1);

    hv_count_obj = 0;
    hv_i = hv_pos+1;
    while (0 != (hv_i<(hv_rec_len-1)))
    {

      //Angle calculation, relative to the first point
      TupleAtan2(HTuple(hv_rec_row[hv_i])-hv_cur_y, HTuple(hv_rec_col[hv_i])-hv_cur_x, 
          &hv_phi);
      TupleFmod(hv_phi, 6.28318, &hv_phi);
      hv_phi = 3.14-hv_phi;

      TupleAbs(hv_phi-hv_cur_phi, &hv_d_phi);
      TupleAbs(HTuple(hv_rec_phi[hv_i])-hv_cur_phi, &hv_d_phi1);

      TuplePow(HTuple(hv_rec_row[hv_i])-hv_cur_y, 2, &hv_powY);
      TuplePow(HTuple(hv_rec_col[hv_i])-hv_cur_x, 2, &hv_powX);
      TupleSqrt(hv_powY+hv_powX, &hv_dist_XY);
      //If less than the threshold - found a rectangle that lies on a straight line
      if (0 != (HTuple(HTuple(hv_d_phi<0.09).TupleAnd(hv_d_phi1<0.07)).TupleAnd(hv_dist_XY<800)))
      {
        //Number of found objects in a line
        hv_count_obj += 1;

        //Let's remember the coordinates
        TupleConcat(hv_line_row1, HTuple(hv_rec_row[hv_i]), &hv_line_row1);
        TupleConcat(hv_line_col1, HTuple(hv_rec_col[hv_i]), &hv_line_col1);

        hv_cur_y = HTuple(hv_rec_row[hv_i]);
        hv_cur_x = HTuple(hv_rec_col[hv_i]);
        //cur_phi := rec_phi[i]

        TupleRemove(hv_rec_col, hv_i, &hv_rec_col);
        TupleRemove(hv_rec_row, hv_i, &hv_rec_row);
        TupleRemove(hv_rec_phi, hv_i, &hv_rec_phi);

      }
      else
      {
        hv_i += 1;

      }

      TupleLength(hv_rec_phi, &hv_rec_len);
    }

    //Found objects > 3, then save the line
    if (0 != (hv_count_obj>=3))
    {

      // stop(...); only in hdevelop

      hv_line_col += 1;
      //gen_region_points (Region, line_row1, line_col1)

      //tuple_length (line_row1, line_len)
      //gen_empty_region (reg_line)
      //*         for k := 1 to line_len - 1 by 1
      //*             gen_region_line(RegionLines, line_row1[k-1], line_col1[k-1], line_row1[k], line_col1[k])
      //*             union2(reg_line, RegionLines, reg_line)

      //dilation_circle (RegionLines, RegionLines_DIL, 6.5)
      //intersection (RegionLines_DIL, Reg_Im_0, reg_line)

      //dev_set_draw ('margin')
      //dev_set_line_width (3)
      //dev_set_color ('red')
      //*             dev_display(RegionLines_DIL)
      //*         endfor
      //*         dilation_circle(reg_line, reg_line_DIL, 6.5)

      GenRegionPolygon(&ho_Region1, hv_line_row1, hv_line_col1);
      DilationCircle(ho_Region1, &ho_Region1_DIL, 6.5);

      if (HDevWindowStack::IsOpen())
        SetDraw(HDevWindowStack::GetActive(),"margin");
      if (HDevWindowStack::IsOpen())
        SetLineWidth(HDevWindowStack::GetActive(),3);
      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),"red");
      if (HDevWindowStack::IsOpen())
        DispObj(ho_Region1_DIL, HDevWindowStack::GetActive());


    }

    //Let's clean up the blunts. TODO: in c/c++ store as a line in an array.
    hv_line_row1 = HTuple();
    hv_line_col1 = HTuple();
    hv_pos += 1;
  }


  // stop(...); only in hdevelop







}


#ifndef NO_EXPORT_APP_MAIN

#ifdef __APPLE__
// On OS X systems, we must have a CFRunLoop running on the main thread in
// order for the HALCON graphics operators to work correctly, and run the
// action function in a separate thread. A CFRunLoopTimer is used to make sure
// the action function is not called before the CFRunLoop is running.
// Note that starting with macOS 10.12, the run loop may be stopped when a
// window is closed, so we need to put the call to CFRunLoopRun() into a loop
// of its own.
HTuple      gStartMutex;
H_pthread_t gActionThread;
HBOOL       gTerminate = FALSE;

static void timer_callback(CFRunLoopTimerRef timer, void *info)
{
  UnlockMutex(gStartMutex);
}

static Herror apple_action(void **parameters)
{
  // Wait until the timer has fired to start processing.
  LockMutex(gStartMutex);
  UnlockMutex(gStartMutex);

  try
  {
    action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
  }

  // Tell the main thread to terminate itself.
  LockMutex(gStartMutex);
  gTerminate = TRUE;
  UnlockMutex(gStartMutex);
  CFRunLoopStop(CFRunLoopGetMain());
  return H_MSG_OK;
}

static int apple_main(int argc, char *argv[])
{
  Herror                error;
  CFRunLoopTimerRef     Timer;
  CFRunLoopTimerContext TimerContext = { 0, 0, 0, 0, 0 };

  CreateMutex("type","sleep",&gStartMutex);
  LockMutex(gStartMutex);

  error = HpThreadHandleAlloc(&gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleAlloc failed: %d\n", error);
    exit(1);
  }

  error = HpThreadCreate(gActionThread,0,apple_action);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadCreate failed: %d\n", error);
    exit(1);
  }

  Timer = CFRunLoopTimerCreate(kCFAllocatorDefault,
                               CFAbsoluteTimeGetCurrent(),0,0,0,
                               timer_callback,&TimerContext);
  if (!Timer)
  {
    fprintf(stderr,"CFRunLoopTimerCreate failed\n");
    exit(1);
  }
  CFRunLoopAddTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);

  for (;;)
  {
    HBOOL terminate;

    CFRunLoopRun();

    LockMutex(gStartMutex);
    terminate = gTerminate;
    UnlockMutex(gStartMutex);

    if (terminate)
      break;
  }

  CFRunLoopRemoveTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);
  CFRelease(Timer);

  error = HpThreadHandleFree(gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleFree failed: %d\n", error);
    exit(1);
  }

  ClearMutex(gStartMutex);
  return 0;
}
#endif

int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#elif defined(__linux__) && (defined(__i386__) || defined(__x86_64__))
    XInitThreads();
#endif

    // file was stored with local-8-bit encoding
    //   -> set the interface encoding accordingly
    SetHcppInterfaceStringEncodingIsUtf8(false);

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

#ifndef __APPLE__
    action();
#else
    ret = apple_main(argc,argv);
#endif
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
    ret = 1;
  }
  return ret;
}

#endif


#endif


