///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 18.11.0.1
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp949).
// Ensure that the interface encoding is set to locale encoding by calling
// SetHcppInterfaceStringEncodingIsUtf8(false) at the beginning of the program.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#  if defined(__linux__) && (defined(__i386__) || defined(__x86_64__)) \
                         && !defined(NO_EXPORT_APP_MAIN)
#    include <X11/Xlib.h>
#  endif
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#  include <stdio.h>
#  include <HALCON/HpThread.h>
#  include <CoreFoundation/CFRunLoop.h>
#endif



using namespace HalconCpp;

// Procedure declarations 
// External procedures 
// Chapter: Matching / Correlation-Based
// Short Description: Display the results of Correlation-Based Matching. 
void dev_display_ncc_matching_results (HTuple hv_ModelID, HTuple hv_Color, HTuple hv_Row, 
    HTuple hv_Column, HTuple hv_Angle, HTuple hv_Model);
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ();

// Procedures 
// External procedures 
// Chapter: Matching / Correlation-Based
// Short Description: Display the results of Correlation-Based Matching. 
void dev_display_ncc_matching_results (HTuple hv_ModelID, HTuple hv_Color, HTuple hv_Row, 
    HTuple hv_Column, HTuple hv_Angle, HTuple hv_Model)
{

  // Local iconic variables
  HObject  ho_ModelRegion, ho_ModelContours, ho_ContoursAffinTrans;
  HObject  ho_Cross;

  // Local control variables
  HTuple  hv_NumMatches, hv_Index, hv_Match, hv_HomMat2DIdentity;
  HTuple  hv_HomMat2DRotate, hv_HomMat2DTranslate, hv_RowTrans;
  HTuple  hv_ColTrans;

  //This procedure displays the results of Correlation-Based Matching.
  //
  hv_NumMatches = hv_Row.TupleLength();
  if (0 != (hv_NumMatches>0))
  {
    if (0 != ((hv_Model.TupleLength())==0))
    {
      TupleGenConst(hv_NumMatches, 0, &hv_Model);
    }
    else if (0 != ((hv_Model.TupleLength())==1))
    {
      TupleGenConst(hv_NumMatches, hv_Model, &hv_Model);
    }
    {
    HTuple end_val9 = (hv_ModelID.TupleLength())-1;
    HTuple step_val9 = 1;
    for (hv_Index=0; hv_Index.Continue(end_val9, step_val9); hv_Index += step_val9)
    {
      GetNccModelRegion(&ho_ModelRegion, HTuple(hv_ModelID[hv_Index]));
      GenContourRegionXld(ho_ModelRegion, &ho_ModelContours, "border_holes");
      if (HDevWindowStack::IsOpen())
        SetColor(HDevWindowStack::GetActive(),HTuple(hv_Color[hv_Index%(hv_Color.TupleLength())]));
      {
      HTuple end_val13 = hv_NumMatches-1;
      HTuple step_val13 = 1;
      for (hv_Match=0; hv_Match.Continue(end_val13, step_val13); hv_Match += step_val13)
      {
        if (0 != (hv_Index==HTuple(hv_Model[hv_Match])))
        {
          HomMat2dIdentity(&hv_HomMat2DIdentity);
          HomMat2dRotate(hv_HomMat2DIdentity, HTuple(hv_Angle[hv_Match]), 0, 0, &hv_HomMat2DRotate);
          HomMat2dTranslate(hv_HomMat2DRotate, HTuple(hv_Row[hv_Match]), HTuple(hv_Column[hv_Match]), 
              &hv_HomMat2DTranslate);
          AffineTransContourXld(ho_ModelContours, &ho_ContoursAffinTrans, hv_HomMat2DTranslate);
          if (HDevWindowStack::IsOpen())
            DispObj(ho_ContoursAffinTrans, HDevWindowStack::GetActive());
          AffineTransPixel(hv_HomMat2DTranslate, 0, 0, &hv_RowTrans, &hv_ColTrans);
          GenCrossContourXld(&ho_Cross, hv_RowTrans, hv_ColTrans, 6, HTuple(hv_Angle[hv_Match]));
          if (HDevWindowStack::IsOpen())
            DispObj(ho_Cross, HDevWindowStack::GetActive());
        }
      }
      }
    }
    }
  }
  return;
}

// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
void dev_update_off ()
{

  //This procedure sets different update settings to 'off'.
  //This is useful to get the best performance and reduce overhead.
  //
  // dev_update_pc(...); only in hdevelop
  // dev_update_var(...); only in hdevelop
  // dev_update_window(...); only in hdevelop
  return;
}

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local iconic variables
  HObject  ho_Img_Im, ho_Reg_Im, ho_REG_Eyes2, ho_REG_Eyes3;
  HObject  ho_ERec, ho_Reg_Im_0, ho_Reg_Im_ER, ho_Reg_Im_CON;
  HObject  ho_Region, ho_RegionLines, ho_RegionLines_DIL, ho_reg_line;
  HObject  ho_ROI_0, ho_ImageReduced, ho_ROI_1, ho_Img_Im_RED;

  // Local control variables
  HTuple  hv_path, hv_path1, hv_Row, hv_Column;
  HTuple  hv_Length1, hv_Length2, hv_rec_row, hv_rec_col;
  HTuple  hv_rec_phi, hv_line_row1, hv_line_col1, hv_line_row2;
  HTuple  hv_line_col2, hv_line_col, hv_rec_len, hv_pos, hv_cur_phi;
  HTuple  hv_cur_y, hv_cur_x, hv_count_obj, hv_i, hv_phi;
  HTuple  hv_d_phi, hv_d_phi1, hv_powY, hv_powX, hv_dist_XY;
  HTuple  hv_line_len, hv_k, hv_ModelID, hv_Angle, hv_Score;

  dev_update_off();
  hv_path = "C:/Work/Data/Scratch & Other/Scratch/";
  hv_path1 = "C:/Work/Data/Scratch & Other/249/";


  ReadImage(&ho_Img_Im, hv_path1+"Im.tif");
  //read_image (Img_Im1, path1 + 'Im.tif')
  // stop(...); only in hdevelop


  //threshold (Img_Im, Reg_Im, 235, 255)

  //closing_circle (Reg_Im, Reg_Im_CLS, 3.5)
  //complement (Reg_Im, Reg_Im_INV)

  //* difference(Reg_Im_CLS, Reg_Im, REG_DIFF)
  //* connection(REG_DIFF, REG_DIFF_CON)
  //* select_shape(REG_DIFF_CON, REG_DIFF_CON_Eyes, 'area', 'or',  120, 100000)

  //stop ()

  //threshold (Img_Im, Reg_Im1, 253, 255)
  //* connection(Reg_Im1, Reg_Im_CON1)
  //* select_shape(Reg_Im_CON1, REG_Eyes1, 'struct_factor', 'or',  8, 300)
  //erosion_circle (REG_Eyes1, REG_Eyes1_CLS, 1.5)
  //connection (REG_Eyes1_CLS, REG_Eyes1_CLS)
  //select_shape (REG_Eyes1_CLS, REG_Eyes2, 'struct_factor', 'or', 10, 300)
  //select_shape (REG_Eyes2, REG_Eyes3, 'area', 'or', 6, 100000)

  //smallest_rectangle2 (REG_Eyes3, Row, Column, Phi, Length1, Length2)
  //gen_rectangle2 (ERec, Row, Column, Phi, Length1, Length2)

  //stop ()

  //* dilation_circle(REG_DIFF_CON_Eyes, REG_DIFF_DIL, 3.2)
  //* dilation_circle(REG_Eyes, REG_Eyes_DIL, 3.2)

  //* intersection(REG_DIFF_DIL, REG_Eyes_DIL, REG_INTER)
  //select_shape (REG_INTER, REG_INTER, 'area', 'or', 100, 100000)
  //stop ()
  //union1 (REG_INTER, REG_INTER)
  //connection (REG_INTER, REG_INTER)

  //* select_shape(REG_INTER, REG_Eyes1, 'struct_factor', 'or',  7, 300)
  //select_shape (REG_Eyes1, REG_Eyes2, 'contlength', 'or', 30, 3000)

  //stop ()


  //** ------------ ¬±¬à¬Ú¬ã¬Ü ¬á¬â¬Ö¬Õ¬Ó¬Ñ¬â¬Ú¬ä¬Ö¬Ý¬î¬ß¬í¬Û ------------------
  Threshold(ho_Img_Im, &ho_Reg_Im_0, 100, 255);
  Threshold(ho_Img_Im, &ho_Reg_Im, 253, 255);
  ErosionCircle(ho_Reg_Im, &ho_Reg_Im_ER, 1.1);
  Connection(ho_Reg_Im_ER, &ho_Reg_Im_CON);
  //select_shape (Reg_Im_CON, Reg_Im_CON, 'area', 'or', 6, 100000)
  //select_shape (Reg_Im_CON, REG_Eyes1, 'struct_factor', 'or', 6, 3000)
  SelectShape(ho_Reg_Im_CON, &ho_REG_Eyes2, "struct_factor", "or", 12, 300);
  SelectShape(ho_REG_Eyes2, &ho_REG_Eyes3, "area", "or", 16, 100000);



  //** ------------ ¬±¬à¬Ú¬ã¬Ü ¬á¬â¬Ö¬Õ¬Ó¬Ñ¬â¬Ú¬ä¬Ö¬Ý¬î¬ß¬í¬Û ------------------
  //threshold (Img_Im, Reg_Im, 253, 255)
  //connection (Reg_Im, Reg_Im_CON)
  //select_shape (Reg_Im_CON, Reg_Im_CON, 'area', 'or', 60, 100000)
  //select_shape (Reg_Im_CON, REG_Eyes1, 'struct_factor', 'or', 6, 3000)
  //erosion_circle (REG_Eyes1, REG_Eyes1_CLS, 1.5)
  //erosion_circle (Reg_Im_CON, REG_Eyes1_CLS, 1.5)
  //connection (REG_Eyes1_CLS, REG_Eyes1_CLS)
  //* select_shape(REG_Eyes1_CLS, REG_Eyes2, 'struct_factor', 'or',  8, 300)
  //select_shape (REG_Eyes2, REG_Eyes3, 'area', 'or', 6, 100000)

  // stop(...); only in hdevelop

  //** ------------ ¬±¬à¬Ú¬ã¬Ü ¬à¬Ò¬ì¬Ö¬Ü¬ä¬à¬Ó ¬ß¬Ñ ¬à¬Õ¬ß¬à¬Û ¬Ý¬Ú¬ß¬Ú¬Ú -----------
  //--- ¬±¬Ö¬â¬Ö¬Ò¬Ú¬â¬Ñ¬Ö¬Þ ¬Ó¬ã¬Ö ¬à¬Ò¬ì¬Ö¬Ü¬ä¬í ¬â¬Ö¬Ô¬Ú¬à¬ß¬à¬Ó ¬Ú ¬Ú¬ë¬Ö¬Þ ¬ä¬Ö, ¬Ü¬à¬ä¬à¬â¬í¬Ö ¬Ý¬Ö¬Ø¬Ñ¬ä ¬ß¬Ñ ¬à¬Õ¬ß¬à¬Û ¬Ý¬Ú¬ß¬Ú¬Ú
  SmallestRectangle2(ho_REG_Eyes3, &hv_rec_row, &hv_rec_col, &hv_rec_phi, &hv_Length1, 
      &hv_Length2);
  GenRectangle2(&ho_ERec, hv_rec_row, hv_rec_col, hv_rec_phi, hv_Length1, hv_Length2);
  if (HDevWindowStack::IsOpen())
    SetDraw(HDevWindowStack::GetActive(),"margin");
  if (HDevWindowStack::IsOpen())
    SetLineWidth(HDevWindowStack::GetActive(),6);
  if (HDevWindowStack::IsOpen())
    SetColor(HDevWindowStack::GetActive(),"blue");
  if (HDevWindowStack::IsOpen())
    DispObj(ho_Img_Im, HDevWindowStack::GetActive());
  //dev_display (ERec)


  hv_line_row1 = HTuple();
  hv_line_col1 = HTuple();
  hv_line_row2 = HTuple();
  hv_line_col2 = HTuple();

  //- ¬±¬à ¬Ó¬ã¬Ö¬Þ ¬ß¬Ñ¬Û¬Õ¬Ö¬ß¬ß¬í¬Þ ¬à¬Ò¬ì¬Ö¬Ü¬ä¬Ñ¬Þ
  //¬¬¬à¬Ý¬Ú¬é¬Ö¬ã¬ä¬Ó¬à ¬ß¬Ñ¬Û¬Õ¬Ö¬ß¬í¬ç ¬Ý¬Ú¬ß¬Ú¬Û
  hv_line_col = 0;
  TupleLength(hv_rec_phi, &hv_rec_len);
  hv_pos = 0;
  while (0 != (hv_pos<(hv_rec_len-1)))
  {

    hv_cur_phi = HTuple(hv_rec_phi[hv_pos]);
    hv_cur_y = HTuple(hv_rec_row[hv_pos]);
    hv_cur_x = HTuple(hv_rec_col[hv_pos]);

    //¬ª¬ß¬Ú¬è¬Ú¬Ñ¬Ý¬Ú¬Ù¬Ñ¬è¬Ú¬ñ ¬Ü¬à¬à¬â¬Õ¬Ú¬ß¬Ñ¬ä
    TupleConcat(hv_line_row1, hv_cur_y, &hv_line_row1);
    TupleConcat(hv_line_col1, hv_cur_x, &hv_line_col1);

    hv_count_obj = 0;
    hv_i = hv_pos+1;
    while (0 != (hv_i<(hv_rec_len-1)))
    {

      //¬£¬í¬é¬Ú¬ã¬Ý¬Ö¬ß¬Ú¬Ö ¬å¬Ô¬Ý¬Ñ, ¬à¬ä¬ß¬à¬ã¬Ú¬ä¬Ö¬Ý¬î¬ß¬à ¬á¬Ö¬â¬Ó¬à¬Û ¬ä¬à¬é¬Ü¬Ú
      TupleAtan2(HTuple(hv_rec_row[hv_i])-hv_cur_y, HTuple(hv_rec_col[hv_i])-hv_cur_x, 
          &hv_phi);
      TupleFmod(hv_phi, 6.28318, &hv_phi);
      hv_phi = 3.14-hv_phi;

      TupleAbs(hv_phi-hv_cur_phi, &hv_d_phi);
      TupleAbs(HTuple(hv_rec_phi[hv_i])-hv_cur_phi, &hv_d_phi1);

      TuplePow(HTuple(hv_rec_row[hv_i])-hv_cur_y, 2, &hv_powY);
      TuplePow(HTuple(hv_rec_col[hv_i])-hv_cur_x, 2, &hv_powX);
      TupleSqrt(hv_powY+hv_powX, &hv_dist_XY);
      //¬¦¬ã¬Ý¬Ú ¬Þ¬Ö¬ß¬î¬ê¬Ö ¬á¬à¬â¬à¬Ô¬Ñ - ¬ß¬Ñ¬ê¬Ý¬Ú ¬á¬â¬ñ¬Þ¬à¬å¬Ô¬à¬Ý¬î¬ß¬Ú¬Ü, ¬Ü¬à¬ä¬à¬â¬í¬Û ¬Ý¬Ö¬Ø¬Ú¬ä ¬ß¬Ñ ¬á¬â¬ñ¬Þ¬à¬Û
      if (0 != (HTuple(HTuple(hv_d_phi<0.09).TupleAnd(hv_d_phi1<0.20)).TupleAnd(hv_dist_XY<1500)))
      {
        //¬¬¬à¬Ý¬Ú¬é¬Ö¬ã¬ä¬Ó¬à ¬ß¬Ñ¬Û¬Õ¬Ö¬ß¬í¬ç ¬à¬Ò¬ì¬Ö¬Ü¬ä¬à¬Ó ¬Ó ¬Ý¬Ú¬ß¬Ú¬Ú
        hv_count_obj += 1;

        //¬©¬Ñ¬á¬à¬Þ¬ß¬Ú¬Þ ¬Ü¬à¬à¬â¬Õ¬Ú¬ß¬Ñ¬ä¬í
        TupleConcat(hv_line_row1, HTuple(hv_rec_row[hv_i]), &hv_line_row1);
        TupleConcat(hv_line_col1, HTuple(hv_rec_col[hv_i]), &hv_line_col1);

        hv_cur_y = HTuple(hv_rec_row[hv_i]);
        hv_cur_x = HTuple(hv_rec_col[hv_i]);

        TupleRemove(hv_rec_col, hv_i, &hv_rec_col);
        TupleRemove(hv_rec_row, hv_i, &hv_rec_row);
        TupleRemove(hv_rec_phi, hv_i, &hv_rec_phi);

      }
      else
      {
        hv_i += 1;

      }

      TupleLength(hv_rec_phi, &hv_rec_len);
    }

    //¬¯¬Ñ¬Û¬Õ¬Ö¬ß¬ß¬í¬ç ¬à¬Ò¬ì¬Ö¬Ü¬ä¬à¬Ó >= 3, ¬ä¬à ¬ã¬à¬ç¬â¬Ñ¬ß¬Ú¬Þ ¬Ý¬Ú¬ß¬Ú¬ð
    if (0 != (hv_count_obj>=3))
    {
      hv_line_col += 1;
      GenRegionPoints(&ho_Region, hv_line_row1, hv_line_col1);

      TupleLength(hv_line_row1, &hv_line_len);
      {
      HTuple end_val150 = hv_line_len-1;
      HTuple step_val150 = 1;
      for (hv_k=1; hv_k.Continue(end_val150, step_val150); hv_k += step_val150)
      {
        GenRegionLine(&ho_RegionLines, HTuple(hv_line_row1[hv_k-1]), HTuple(hv_line_col1[hv_k-1]), 
            HTuple(hv_line_row1[hv_k]), HTuple(hv_line_col1[hv_k]));
        DilationCircle(ho_RegionLines, &ho_RegionLines_DIL, 6.5);
        Intersection(ho_RegionLines_DIL, ho_Reg_Im_0, &ho_reg_line);

        if (HDevWindowStack::IsOpen())
          SetDraw(HDevWindowStack::GetActive(),"margin");
        if (HDevWindowStack::IsOpen())
          SetLineWidth(HDevWindowStack::GetActive(),3);
        if (HDevWindowStack::IsOpen())
          SetColor(HDevWindowStack::GetActive(),"red");
        if (HDevWindowStack::IsOpen())
          DispObj(ho_reg_line, HDevWindowStack::GetActive());
      }
      }

    }

    //¬°¬é¬Ú¬ã¬ä¬Ú¬Þ ¬ä¬å¬á¬Ý¬í. TODO: ¬Ó ¬ã/¬ã++ ¬ã¬à¬ç¬â¬Ñ¬ß¬Ú¬ä¬î ¬Ü¬Ñ¬Ü ¬Ý¬Ú¬ß¬Ú¬ð ¬Ó ¬Þ¬Ñ¬ã¬ã¬Ú¬Ó¬Ö.
    hv_line_row1 = HTuple();
    hv_line_col1 = HTuple();
    hv_pos += 1;
  }



  //gen_rectangle1 (Rectangle, line_row1, line_col1, line_row2, line_col2)


  // stop(...); only in hdevelop

  //** ------------ ¬±¬à¬Ú¬ã¬Ü ¬Ü¬à¬â¬â¬Ö¬Ý¬ñ¬è¬Ú¬Ö¬Û -----------------------
  //--- ¬£¬í¬Ò¬Ú¬â¬Ñ¬Ö¬Þ ¬Ó¬ã¬Ö ¬Ý¬Ú¬ß¬Ú¬Ú ¬ã ¬à¬Ò¬ì¬Ö¬Ü¬ä¬Ñ¬Þ¬Ú ¬Ú ¬â¬Ú¬ã¬å¬Ö¬Þ ¬à¬á¬Ú¬ã¬Ñ¬ß¬ß¬í¬Û ¬Ü¬Ó¬Ñ¬Õ¬â¬Ñ¬ä
  //--- ¬£ ¬á¬â¬Ö¬Õ¬Ö¬Ý¬Ñ¬ç ¬ï¬ä¬à¬Ô¬à ¬Ü¬Ó¬Ñ¬Õ¬â¬Ñ¬ä¬Ñ ¬Ú¬ë¬Ö¬Þ ¬è¬Ñ¬â¬Ñ¬á¬Ú¬ß¬í ¬Ü¬à¬â¬â¬Ö¬Ý¬ñ¬è¬Ú¬Ö¬Û

  GenRectangle2(&ho_ROI_0, 15706.9, 2329.8, HTuple(1.45393).TupleRad(), 17.396, 12.2935);
  //gen_rectangle2 (ROI_0, 15648.7, 2777.38, rad(2.28987), 16.0619, 5.39805)

  ReduceDomain(ho_Img_Im, ho_ROI_0, &ho_ImageReduced);
  //create_shape_model (ImageReduced, 1, 0, rad(360), 'auto', 'none', 'ignore_global_polarilllty', 'auto_contrast', 'auto', ModelID_11)
  CreateNccModel(ho_ImageReduced, 0, HTuple(0).TupleRad(), HTuple(360).TupleRad(), 
      "auto", "use_polarity", &hv_ModelID);



  //gen_rectangle1 (ROI_1, 15051, 3152.23, 15875.8, 4871.48)

  GenRectangle1(&ho_ROI_1, 14532.9, 147.378, 16082.7, 5025.42);
  ReduceDomain(ho_Img_Im, ho_ROI_1, &ho_Img_Im_RED);
  FindNccModel(ho_Img_Im_RED, hv_ModelID, HTuple(-30).TupleRad(), HTuple(30).TupleRad(), 
      0.30, 100, 0.5, "false", 0, &hv_Row, &hv_Column, &hv_Angle, &hv_Score);
  dev_display_ncc_matching_results(hv_ModelID, "red", hv_Row, hv_Column, hv_Angle, 
      0);


  //** ----------------------------------------------




  //count_seconds (time_0)

  //threshold (Img_Im, Reg_Im, 240, 255)
  //threshold (Img_Im, Reg_Im, 190, 230)

  //complement (Reg_Im, Reg_Im_INV)
  //* connection(Reg_Im_INV, Reg_Im_CON_INV)
  //* select_shape(Reg_Im_CON_INV, REG_Eyes_INV, 'area', 'or',  1000, 100000)
  //* union1(REG_Eyes_INV, REG_Eyes_UN_INV)



  //paint_region (Reg_Im_INV, Img_Im, Img_Im_PRT, 200, 'fill')
  //threshold (Img_Im, Reg_Im, 240, 255)


  //connection (Reg_Im, Reg_Im_CON)
  //* select_shape(Reg_Im_CON, REG_Eyes, 'area', 'or',  1000, 100000)
  //union1 (REG_Eyes, REG_Eyes_UN)

  //* select_shape(Reg_Im_CON, REG_Eyes, 'area', 'or',  60, 3000)
  //complement (REG_Eyes, REG_Eyes_INV)
  //closing_circle (REG_Eyes, Reg_Im_CON_CLS, 3.5)
  //difference (Reg_Im_CON_CLS, REG_Eyes, REG_DIFF)


  //dilation_circle (Reg_Im, Reg_Im_DIL, 3.5)
  //erosion_circle (Reg_Im_DIL, Reg_Im_CON_CLS, 3.5)
  //* closing_circle(REG_Eyes_UN, Reg_Im_CON_CLS, 3.5)

  //complement (Reg_Im, REG_Eyes_UN1)
  //stop ()


  //* difference(Reg_Im_CON_CLS, REG_Eyes_UN, REG_DIFF)

  //connection (REG_DIFF, Reg_Im_CON1)
  //select_shape (Reg_Im_CON1, REG_Eyes, 'struct_factor', 'or', 12, 300)
  //select_shape (REG_Eyes, REG_Eyes, 'contlength', 'or', 30, 300)
  //* dilation_circle(REG_Eyes, REG_Eyes_DIL, 20.5)

  //count_seconds (time_1)
  //* time_S := time_1 - time_0

  //union1 (REG_Eyes, REG_Eyes_UN)
  //* dilation_circle(REG_Eyes_UN, REG_Eyes_UN_DIL, 100.5)
  //* erosion_circle(REG_Eyes_UN_DIL, REG_Eyes_UN_ER, 80.5)



  // stop(...); only in hdevelop






}


#ifndef NO_EXPORT_APP_MAIN

#ifdef __APPLE__
// On OS X systems, we must have a CFRunLoop running on the main thread in
// order for the HALCON graphics operators to work correctly, and run the
// action function in a separate thread. A CFRunLoopTimer is used to make sure
// the action function is not called before the CFRunLoop is running.
// Note that starting with macOS 10.12, the run loop may be stopped when a
// window is closed, so we need to put the call to CFRunLoopRun() into a loop
// of its own.
HTuple      gStartMutex;
H_pthread_t gActionThread;
HBOOL       gTerminate = FALSE;

static void timer_callback(CFRunLoopTimerRef timer, void *info)
{
  UnlockMutex(gStartMutex);
}

static Herror apple_action(void **parameters)
{
  // Wait until the timer has fired to start processing.
  LockMutex(gStartMutex);
  UnlockMutex(gStartMutex);

  try
  {
    action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
  }

  // Tell the main thread to terminate itself.
  LockMutex(gStartMutex);
  gTerminate = TRUE;
  UnlockMutex(gStartMutex);
  CFRunLoopStop(CFRunLoopGetMain());
  return H_MSG_OK;
}

static int apple_main(int argc, char *argv[])
{
  Herror                error;
  CFRunLoopTimerRef     Timer;
  CFRunLoopTimerContext TimerContext = { 0, 0, 0, 0, 0 };

  CreateMutex("type","sleep",&gStartMutex);
  LockMutex(gStartMutex);

  error = HpThreadHandleAlloc(&gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleAlloc failed: %d\n", error);
    exit(1);
  }

  error = HpThreadCreate(gActionThread,0,apple_action);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadCreate failed: %d\n", error);
    exit(1);
  }

  Timer = CFRunLoopTimerCreate(kCFAllocatorDefault,
                               CFAbsoluteTimeGetCurrent(),0,0,0,
                               timer_callback,&TimerContext);
  if (!Timer)
  {
    fprintf(stderr,"CFRunLoopTimerCreate failed\n");
    exit(1);
  }
  CFRunLoopAddTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);

  for (;;)
  {
    HBOOL terminate;

    CFRunLoopRun();

    LockMutex(gStartMutex);
    terminate = gTerminate;
    UnlockMutex(gStartMutex);

    if (terminate)
      break;
  }

  CFRunLoopRemoveTimer(CFRunLoopGetCurrent(),Timer,kCFRunLoopCommonModes);
  CFRelease(Timer);

  error = HpThreadHandleFree(gActionThread);
  if (H_MSG_OK != error)
  {
    fprintf(stderr,"HpThreadHandleFree failed: %d\n", error);
    exit(1);
  }

  ClearMutex(gStartMutex);
  return 0;
}
#endif

int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#elif defined(__linux__) && (defined(__i386__) || defined(__x86_64__))
    XInitThreads();
#endif

    // file was stored with local-8-bit encoding
    //   -> set the interface encoding accordingly
    SetHcppInterfaceStringEncodingIsUtf8(false);

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

#ifndef __APPLE__
    action();
#else
    ret = apple_main(argc,argv);
#endif
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            (const char *)exception.ProcName(),
            (const char *)exception.ErrorMessage());
    ret = 1;
  }
  return ret;
}

#endif


#endif


