#-----------------------------------------------------------------------------
# HALCON extension package example "halconuser"
#
# General macro definitions for HALCON extension package examples that are
# independent of the used platform or makefile system.
#
#-----------------------------------------------------------------------------
# Copyright (c) 1996-2018 MVTec Software GmbH, http://www.mvtec.com
#-----------------------------------------------------------------------------

# Name of HALCON user extension package that contains the new operators:
PACKAGE_NAME       = Filt_AMM_04

XPKG_INC           = $(BASE_DIR)include
XPKG_SRC           = $(BASE_DIR)source
XPKG_DEF           = $(BASE_DIR)def
XPKG_HELP          = $(BASE_DIR)help
HELP_NAME          = operators_en_US
XPKG_DOC           = $(BASE_DIR)doc
XPKG_DOC_HTML      = $(XPKG_DOC)$(SL)html
XPKG_DOC_REF       = $(XPKG_DOC_HTML)$(SL)reference

BIN_BASE           = $(BASE_DIR)bin
BIN_DIR            = $(BIN_BASE)$(SL)$(HALCONARCH)
BIN_DIR_DOTNET     = $(BIN_BASE)$(SL)dotnet
LIB_BASE           = $(BASE_DIR)lib
LIB_DIR            = $(LIB_BASE)$(SL)$(HALCONARCH)
LIB_DIR_DOTNET     = $(BIN_BASE)$(SL)dotnet
OBJ_BASE           = $(BASE_DIR)obj
OBJ_BASE_ARCH      = $(OBJ_BASE)$(SL)$(HALCONARCH)
OBJ_DIR            = $(OBJ_BASE)$(SL)$(HALCONARCH)$(SL)$(HSUFFIX)$(SL)
H_INCLUDE          = $(HALCONROOT)$(SL)include
H_INCLUDE_CPP      = $(HALCONROOT)$(SL)include$(SL)halconcpp
H_INCLUDE_CPP10    = $(HALCONROOT)$(SL)include$(SL)cpp
H_LIB              = $(HALCONROOT)$(SL)lib$(SL)$(HALCONARCH)
H_DOTNET           = $(HALCONROOT)$(SL)$(BIN_BASE)$(SL)dotnet20
#HCOMP             = hcomp
HCOMP              = "$(HCOMP_FULL_PATH)"
HCOMP_FULL_PATH    = $(HALCONROOT)$(SL)bin$(SL)$(HALCONARCH)$(SL)hcomp$(EXE)

# Name(s) of new HALCON operator description file(s):
XPKG_DEF_FILES     = $(XPKG_DEF)$(SL)Filt_AMM_04.def 

# Name(s) of new HALCON operator object file(s):
XPKG_OBJS          = $(OBJ_DIR)$(SL)cipuserFilt_AMM_04.$(O) \
		     $(OBJ_DIR)$(SL)H$(PACKAGE_NAME).$(O)
# Base package library also contains the procedure table generated by hcomp

XPKG_LIB_NAME        = $(PACKAGE_NAME)$(HSUFFIX)
XPKG_LIB_C_NAME      = $(PACKAGE_NAME)c$(HSUFFIX)
XPKG_LIB_CPP_NAME    = $(PACKAGE_NAME)cpp$(HSUFFIX)
XPKG_LIB_CPP10_NAME  = $(PACKAGE_NAME)cpp10$(HSUFFIX)
XPKG_LIB_DOTNET_NAME = $(PACKAGE_NAME)dotnet$(HSUFFIX)

XPKG_LIB_H           = $(AR_DIR)$(SL)$(AR_PREFIX)$(XPKG_LIB_NAME).$(AR_EXT)
XPKG_LIB_C           = $(AR_DIR)$(SL)$(AR_PREFIX)$(XPKG_LIB_C_NAME).$(AR_EXT)
XPKG_LIB_CPP         = $(AR_DIR)$(SL)$(AR_PREFIX)$(XPKG_LIB_CPP_NAME).$(AR_EXT)
XPKG_LIB_CPP10       = $(AR_DIR)$(SL)$(AR_PREFIX)$(XPKG_LIB_CPP10_NAME).$(AR_EXT)
XPKG_LIB_DOTNET      = $(LIB_DIR_DOTNET)$(SL)$(XPKG_LIB_DOTNET_NAME).dll

XPKG_C_OBJS          = $(OBJ_DIR)$(SL)HC$(PACKAGE_NAME).$(O)
XPKG_CPP_OBJS        = $(OBJ_DIR)$(SL)HCPP$(PACKAGE_NAME).$(O)
XPKG_CPP10_OBJS      = $(OBJ_DIR)$(SL)HCPP10$(PACKAGE_NAME).$(O)


# -- macros to build a test program
# name of new test application(s) for testing/using the new operators:

#APPLICATION_C        = $(BIN_DIR)$(SL)testthreshold$(HSUFFIX)$(EXE) \
#                       $(BIN_DIR)$(SL)testprint$(HSUFFIX)$(EXE) \
#                       $(BIN_DIR)$(SL)testregionfeatures$(HSUFFIX)$(EXE) \
#                       $(BIN_DIR)$(SL)testfilter$(HSUFFIX)$(EXE)

#APPLICATION_CPP      = $(BIN_DIR)$(SL)testthresholdcpp$(HSUFFIX)$(EXE) \
#                       $(BIN_DIR)$(SL)testregionfeaturescpp$(HSUFFIX)$(EXE) \
#                       $(BIN_DIR)$(SL)testfiltercpp$(HSUFFIX)$(EXE)

APPLICATION_DOTNET_NAME = testthresholddotnet
APPLICATION_DOTNET   = $(BIN_DIR_DOTNET)$(SL)$(APPLICATION_DOTNET_NAME)$(HSUFFIX)_$(HALCONARCH).exe
