/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 13.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HalconAPI.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HalconAPI.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HalconAPI.h>
#  endif
#endif

#include "HCPPFilt_AMM_04.h"

extern "C" HUserImport HINT HFilt_AMM_04GetOffset();

HINT offset = -1;

using namespace HalconCpp;

Hproc_handle PreCallUser(HINT proc_index_local)
{
  if (offset < 0)
  {
    /* First use of this extension package, query my offset */
    offset = HFilt_AMM_04GetOffset();
    if (offset < 0)
    {
      /* HALCON libary not initialized (extension package as first usage). */
      /* Trigger initialization by touching system operator and try again. */
      Hproc_handle tmp = HalconAPI::PreCall(0);
      HalconAPI::PostCall(tmp);
      offset = HFilt_AMM_04GetOffset();
      if (offset < 0)
      {
        /* Ok, so something is *really* wrong */
        HOperatorException::Throw(proc_index_local,H_ERR_UEXTNI);
      }
    }
  }
  return HalconAPI::PreCall(offset + proc_index_local);
}




#ifdef UserFiltAMM04
# error An existing macro name conflicts with UserFiltAMM04
#endif
HUserExport void HalconCpp::UserFiltAMM04(const HTuple& hv_Input, const HTuple& hv_Win_Len, const HTuple& hv_Move_Avg, const HTuple& hv_thrMB, const HTuple& hv_thrSP, HTuple* hv_Tuple_Avg_CMax, HTuple* hv_Tuple_Avg_CMin, HTuple* hv_Tuple_Avg_MM_Th)
{
  Hproc_handle proc = PreCallUser(0);
  HalconAPI::Store(proc,0,hv_Input);
  HalconAPI::Store(proc,1,hv_Win_Len);
  HalconAPI::Store(proc,2,hv_Move_Avg);
  HalconAPI::Store(proc,3,hv_thrMB);
  HalconAPI::Store(proc,4,hv_thrSP);
  HalconAPI::InitOutp(proc,0);
  HalconAPI::InitOutp(proc,1);
  HalconAPI::InitOutp(proc,2);
  HalconAPI::CallProcedure(proc);
  HalconAPI::Load(proc,0,hv_Tuple_Avg_CMax);
  HalconAPI::Load(proc,1,hv_Tuple_Avg_CMin);
  HalconAPI::Load(proc,2,hv_Tuple_Avg_MM_Th);
  HalconAPI::PostCall(proc);
}

